replicaCount: 2

image:
  repository: 979075841935.dkr.ecr.us-east-1.amazonaws.com/eks-gitops-app
  tag: f76f3712a8bfbcaf38a82da7cf5217fd783d28f7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  APP_VERSION: "v1"
